### Health Check
GET http://localhost:8080/api/v1/events/health


### Check Buffer Status
GET http://localhost:8080/api/v1/events/buffer/status


### Check Existing Batches
GET http://localhost:8080/api/v1/events/batches


### Clear Buffer
DELETE http://localhost:8080/api/v1/events/buffer


### Clear Batches
DELETE http://localhost:8080/api/v1/events/batches


### Publish valid event 1 to Kafka
POST http://localhost:8080/api/v1/kafka-test/payment
Content-Type: application/json

{
  "transactionId": "TXN-40001",
  "orderId": "ORD-94001",
  "merchantId": "MER-001",
  "customerId": "CUS-001",
  "amount": 100,
  "currency": "INR",
  "paymentMode": "UPI",
  "paymentStatus": "SUCCESS",
  "eventTimestamp": "2026-05-05T10:00:00Z"
}


### Publish valid event 2 to Kafka
POST http://localhost:8080/api/v1/kafka-test/payment
Content-Type: application/json

{
  "transactionId": "TXN-40002",
  "orderId": "ORD-94002",
  "merchantId": "MER-001",
  "customerId": "CUS-002",
  "amount": 200,
  "currency": "INR",
  "paymentMode": "CARD",
  "paymentStatus": "SUCCESS",
  "eventTimestamp": "2026-05-05T10:01:00Z"
}


### Publish valid event 3 to Kafka
POST http://localhost:8080/api/v1/kafka-test/payment
Content-Type: application/json

{
  "transactionId": "TXN-40003",
  "orderId": "ORD-94003",
  "merchantId": "MER-001",
  "customerId": "CUS-003",
  "amount": 300,
  "currency": "INR",
  "paymentMode": "UPI",
  "paymentStatus": "SUCCESS",
  "eventTimestamp": "2026-05-05T10:02:00Z"
}


### Check Batches After 3 Events
GET http://localhost:8080/api/v1/events/batches


### Publish invalid event to Kafka
POST http://localhost:8080/api/v1/kafka-test/payment
Content-Type: application/json

{
  "transactionId": "",
  "orderId": "ORD-94004",
  "merchantId": "MER-001",
  "customerId": "CUS-004",
  "amount": 400,
  "currency": "INR",
  "paymentMode": "UPI",
  "paymentStatus": "SUCCESS",
  "eventTimestamp": "2026-05-05T10:03:00Z"
}