server.port=8082
spring.application.name=payment-kafka-consumer-service

spring.kafka.bootstrap-servers=localhost:29092
spring.kafka.consumer.group-id=payment-processing-uc5-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer

spring.kafka.listener.ack-mode=record

services.validation.url=http://localhost:8083/api/v1/validation/payment
services.batch-state.url=http://localhost:8084/api/v1/batch-state/events

management.endpoints.web.exposure.include=health,info,metrics

logging.level.root=info
logging.level.com.bl.poc.aggregator=info
logging.level.org.springframework.kafka=info