server.port=8082

spring.application.name=payment-kafka-consumer-service

services.validation.url=http://localhost:3502/v1.0/invoke/payment-validation-service/method/api/v1/validation/payment
services.batch-state.url=http://localhost:3502/v1.0/invoke/payment-batch-state-service/method/api/v1/batch-state/events

management.endpoints.web.exposure.include=health,info,metrics

logging.level.root=info
logging.level.com.bl.poc.aggregator=info