spring.application.name=payment-kafka-consumer-service
server.port=8082

spring.kafka.bootstrap-servers=localhost:29092

spring.kafka.consumer.group-id=payment-processing-uc6-group
spring.kafka.consumer.auto-offset-reset=earliest

spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer

spring.kafka.listener.ack-mode=record

services.validation.url=http://localhost:3502/v1.0/invoke/payment-validation-service/method/api/v1/validation/payment
services.batch-state.url=http://localhost:3502/v1.0/invoke/payment-batch-state-service/method/api/v1/batch-state/events

management.endpoints.web.exposure.include=health,info
logging.level.root=info